### ISSUE TITLE
publish single message to rabbitmq

### ISSUE THREAD

**Issue by jaxxstorm** [upfluence/sensu-client-go#12]
Full disclosure, I'm pretty new to go, so apologies if this is a silly question.

Is it possible, with this lib and https://github.com/upfluence/sensu-go to simply publish a single message to a rabbitmq queue, and then exit, closing the exchange? I want to do something like the local socket extension check but with an external client. 

I'm thinking I can just write a barebone check like the example: https://github.com/upfluence/sensu-client-go#barebone-check but then run client.Stop() immediately after. Is that a reasonable approach, or is there a better way?

**Comment by mihaitodor** [comment]
Hi Lee,

I've been playing with this library a bit lately (I'll submit a PR for improving the documentation soon) and I think you can easily achieve what you want, but not sure why would it be useful for you to exit the client after publishing a message (are you not using RabbitMQ for Sensu monitoring?)

First of all, if you take a look [here](https://github.com/upfluence/sensu-client-go/blob/master/sensu/client.go#L77), you'll notice that all you have to do is start the client in a goroutine and then call [`Close`](https://github.com/upfluence/sensu-go/blob/master/sensu/transport/rabbitmq/rabbitmq.go#L63) on the [transport](https://github.com/upfluence/sensu-client-go/blob/master/sensu-client.go#L17) after your check has finished running. Now, I'm not 100% sure how you can avoid synchronization issues with this approach, so you might have to implement your own [`Transport`](https://github.com/upfluence/sensu-go/blob/master/sensu/transport/transport.go) which has the required synchronization logic inside [`Publish`](https://github.com/upfluence/sensu-go/blob/master/sensu/transport/transport.go#L7), but I'm not sure if there is a simpler way. Maybe @AlexisMontagne has more insight.

Since #6 you can use the Standalone Check Sensu mechanism in order to publish a Sensu payload directly from the client (but I'm not sure this is what you want). You can simply use a check like this:

``` json
{
    "checks": [{
        "name": "one_time_check",
        "standalone": true,
        "interval": 60,
        "extension": "true"
    }]
}
```

on the client side and pass it to your Go client via the -c command line argument. Or, as an alternative, you can emulate the code from [here](https://github.com/upfluence/sensu-client-go/blob/master/sensu/config.go#L41) and construct the [`Config`](https://github.com/upfluence/sensu-client-go/blob/master/sensu/config.go#L20) structure manually.

Hope this helps.

Regards,
Mihai

**Comment by jaxxstorm** [comment]
@mihaitodor thanks for replying!

To provide a bit more insight, I wrote a golang wrapper here https://github.com/jaxxstorm/sensu-wrapper

It uses the concept of [proxy-clients](https://sensuapp.org/docs/latest/reference/clients.html#proxy-clients) to send some JSON to a sensu socket and create checks in sensu. It's designed to execute a command in say, a cron job.

This works great if you're running sensu wrapper alongside a listening sensu-client, but what I'm looking to do is send messages onto a rabbitmq exchange, so that devices that _can't_ run sensu but can run golang binaries can also use this fire and forget method.

So I don't necessarily need a _whole_ client, I just need to connect to an exchange, create a queue, send a message, then tear the whole thing down. Is this reasonably feasible? It seems it could be, not sure.

**Comment by mihaitodor** [comment]
Well, then you have two options:
- use this client to replace your golang wrapper and sensu-client combo. It should be easy enough to get it to work and I guess it wouldn't be a big problem to have it running all the time, given that you already have a sensu-client instance doing just that
- make use of https://github.com/streadway/amqp and build your own socket handler just like [here](https://github.com/upfluence/sensu-go/blob/master/sensu/transport/rabbitmq/rabbitmq.go) I guess this solution is more flexible, but you'll probably have to spend more time figuring out what the Sensu server expects to receive.

PS: Beware of [this issue](https://github.com/streadway/amqp/issues/154). It's still not fixed in the streadway/amqp library and it's quite annoying...

**Comment by AlexisMontagne** [comment]
Hello Lee,

[Here](https://gist.github.com/AlexisMontagne/0e61785913d766b006df94513afd6c0a) is an example of a program sending a single `CheckResponse` to a RabbitMQ exchange and exit right after. I think, it is what you are looking for.

⚠️  When you call `(*RabbitMQTransport).Close()`, the exchange is not destroyed. Only the connection and the channel are closed properly.

**Comment by mihaitodor** [comment]
That was easier than I expected :)

**Comment by jaxxstorm** [comment]
@AlexisMontagne this is amazing, thanks!

**Comment by jaxxstorm** [comment]
Hey @AlexisMontagne sorry for reopening this, but I finally got round to testing this and it seems there's an issue.

When using the sample code, it successfully posts the result to the results queue, but it crashes the server that tries to work with the request:

```
{"timestamp":"2016-11-20T16:49:53.151533+0000","level":"warn","message":"reconnecting to redis"}
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings/loader.rb:184:in `definition_exists?': undefined method `to_sym' for nil:NilClass (NoMethodError)
Did you mean?  to_s
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings/loader.rb:62:in `block (2 levels) in create_category_methods'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/server/process.rb:575:in `block in process_check_result'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/server/process.rb:547:in `block in retrieve_client'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-1.4.0/lib/sensu/redis/client.rb:315:in `dispatch_response'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-1.4.0/lib/sensu/redis/client.rb:337:in `parse_response_line'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-1.4.0/lib/sensu/redis/client.rb:365:in `receive_data'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/server/process.rb:31:in `run'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/exe/sensu-server:10:in `<top (required)>'
    from /opt/sensu/bin/sensu-server:22:in `load'
    from /opt/sensu/bin/sensu-server:22:in `<main>'
```

Am I missing something here?

**Comment by AlexisMontagne** [comment]
Hello Lee, 

I've looked into the Sensu server source code, You can see [here](https://github.com/sensu/sensu/blob/v0.25.3/lib/sensu/server/process.rb#L575), you need to specify a check name to look up into the settings if the check is already registered.

I have updated my gist according to this requirement: https://gist.github.com/AlexisMontagne/0e61785913d766b006df94513afd6c0a

**Comment by AlexisMontagne** [comment]
Hello @jaxxstorm,

Did it work? I will close the issue, feel free to re open it if you still are experiencing troubles.
